# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Tá Safo Conf 2015"
email: "comunidadetasafo@gmail.com"
description: "O Maior evento de tecnologia do Norte do Brasil"
baseurl: ""
url: "http://conf2015.tasafo.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-64707794-1"
googleAnalyticsSiteUrl: "conf2015.tasafo.org"
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Tá Safo!"
organizerAlternateName: "Comunidade Tá Safo!"
organizerDescription: "Tecnologias Abertas com Software Ágil, Fácil e Organizado."
organizerEmail: "comunidadetasafo@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://tasafo.org"

# Head
metaKeywords: "evento, tasafo, tasafoconf, agilidade, programação, desenvolvimento, comunidade, software, gestão"
twitterAccount: "@tasafo"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/PropostaPatrocinio-TasafoConf2015.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 #- {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Programação"}
 - {permalink: "/speakers/", text: "Palestrantes"}
 - {permalink: "/about/", text: "Sobre"}
 - {permalink: "/logistics/", text: "Logística"}
 - {permalink: "/tickets/", text: "Ingressos"}
 #- {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Seja um palestrante"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/1gU5lRD453dvME9C9dEeJNocELrTXTTFWeYtvfdx24Q0/viewform", text: "Seja um palestrante"}
 - {link: "http://conf2015.tasafo.org/assets/PropostaPatrocinio-TasafoConf2015.pdf", text: "Seja um patrocinador"}
 - {link: "https://eventioz.com.br/e/ta-safo-conf-2015", text: "Ingressos"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Tá Safo Conf <typeout> 2015"
eventDate: "21 de Novembro de 2015"
typeoutTextValues: '"", "", "", "", ""'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://docs.google.com/forms/d/1gU5lRD453dvME9C9dEeJNocELrTXTTFWeYtvfdx24Q0/viewform", text: "Seja um palestrante"}
 - {link: "http://conf2015.tasafo.org/assets/PropostaPatrocinio-TasafoConf2015.pdf", text: "Seja um patrocinador"}
 - {link: "https://eventioz.com.br/e/ta-safo-conf-2015", text: "Ingressos"}

# About Block
aboutTitle: "Sobre o Tá Safo Conf"
aboutBlock:
 - {title: "Edgar Silva", position: "Vice-Presidente e Country Manager para o Brasil na WSO2", image: "edgar.jpeg", text: "É uma oportunidade única poder participar do Tá Safo Conf, e eu como um paraense assumidamente papa-chibé, comedor de açaí com farinha, que toma tacacá com muita pimenta, ex-morador da Cidade Nova, estar perto dos meus conterrâneos, meu sotaque é sem sombra de dúvidas um privilégio." }
 - {title: "Alexandre Magno", position: "Learning 3.0 Founder at Happy Melly", image: "magno.jpg", text: "O Tá Safo Conf é um evento rico em colaboração e que tem a cara de uma das comunidades mais atuantes do país. Eu fui e recomendo!" }
 - {title: "Carlos Souza", position: "Instructor at Code School", image: "caike.jpeg", text: "O Tá Safo Conf reune conteúdo atual e relevante tanto a profissionais atuantes no mercado de trabalho quanto àqueles que estão na academia." }
 - {title: "Manoel Pimentel", position: "Agile Coach at Adaptworks", image: "manoel.jpeg", text: "O Tá Safo Conf é um verdadeiro Círio da comunidade de TI paraense - Atrai romeiros de TI do Brasil inteiro para socializar suas experiências e histórias sobre novidades e tendências da área de tecnologia." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 #- {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "1", specialCharacter: "+", info: "dia", detail: "de forte aprendizado"}
 - {count: "30", specialCharacter: "+", info: "palestrantes", detail: "da terra e convidados especiais"}
 - {count: "4", specialCharacter: "", info: "trilhas", detail: "de puro entretenimento e troca de experiências"}

# Latest News Block
latestNewsTitle: "Últimas notícias"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Palestrantes"
rockstarSpeakersButtonText: "Veja todos os palestrantes"

# Location Block
locationBlockTitle: "Local"
eventLocationName: "Centro de Convenções e Feiras da Amazônia - Hangar"
eventLocationLink: "http://www.hangarcentrodeconvencoes.com.br/"
eventStreetAddress: "Av. Dr. Freitas, s/n - Marco"
eventAddressLocality: "Belém"
eventAddressLocalityRegion: "Pará"
eventPostalCode: "66613-902"
eventAddressCountry: "Brasil"
eventStartTime: "2015-11-21T08:00"
eventDoorTime: "09:00"
eventEndTime: "2015-11-21T18:00"
eventPlaceCoordinates: "-1.421725, -48.456777"
mapCenterCoordinates: "-1.421725, -48.456777"
mapMobileCenterCoordinates: "-1.421725, -48.456777"

# Venue Block
venueBlockTitle: "Local"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Centro de Convenções e Feiras da Amazônia - Hangar"
#venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Tá safo?"
twitterHashTag: "tasafoconf"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Seja um patrocinador"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Investimento"
ticketsInfo: "Os ingressos garantem acesso a todas as seções da conferência, coffee breaks e kits."
ticketsOffers:
 -
  name: "Super early bird"
  price: "90"
  priceCurrency: "R$"
  ticketsNumber: "100"
  ribbon: "-5%"
  buyButtonLink: "https://eventioz.com.br/e/ta-safo-conf-2015"
  buyButtonText: "Compre Agora"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2015-08-25T10:00"
  validThrough: "2015-08-31T19:59"
  soldOut: true
 -
  name: "Early bird"
  price: "100"
  priceCurrency: "R$"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "https://eventioz.com.br/e/ta-safo-conf-2015"
  buyButtonText: "Compre agora"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2015-08-31T20:00"
  validThrough: "2015-10-23T23:59"
  disabled: false
 -
  name: "Preço normal"
  price: "120"
  priceCurrency: "R$"
  ticketsNumber: ""
  buyButtonLink: "https://eventioz.com.br/e/ta-safo-conf-2015"
  buyButtonText: "Buy Now"
  # additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2015-10-23T22:00"
  validThrough: "2015-11-20T23:59"
  # soldOut: true
  disabled: true
  # soldOutText: "Sold Out"
 -
  name: "Última hora"
  price: "150"
  priceCurrency: "R$"
  ticketsNumber: ""
  buyButtonLink: "https://eventioz.com.br/e/ta-safo-conf-2015"
  buyButtonText: "Buy Now"
  # additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2015-08-20T10:00"
  validThrough: "2015-10-23T23:59"
  # soldOut: true
  disabled: true

# Footer
socialLinks:
 - {link: "https://plus.google.com/u/0/communities/110035015534021388546", icon: "google-plus"}
 - {link: "https://twitter.com/tasafo", icon: "twitter"}
 - {link: "https://facebook.com/tasafo.comunidade", icon: "facebook"}
 #- {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://tasafo.org", text: "Tá Safo!"}
 -
  title: "Contatos"
  links:
   - {link: "mailto:comunidadetasafo@gmail.com", text: "comunidadetasafo@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de conduta"}

# Blog
blogTitle: "Últimas notícias"
blogCommentsEnabled: true
#discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre nós"
aboutUs: "Pessoas engajadas da comunidade Tá Safo!"

# Logistics Find Way Block
findWayTitle: "Encontre seu caminho"
findWayDistance: "Distância"
findWayDriving: "Dirigindo"
findWayWalking: "Caminhando"
findWayBicycling: "De bike"
findWayTransit: "Trânsito"
findWayFindFlight: "Encontre um vôo"
logisticsMapCenterCoordinates: "-2.7405867, -58.5522087"
logisticsMapMobileCenterCoordinates: "-2.7405867, -58.5522087"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Santa Maria de Belém do Grão Pará"
directionDetailsCards:
 - {title: "Do aeroporto", information: 'O Aeroporto Internacional - Val de Cans, serve a cidade brasileira de Belém, capital do estado do Pará. É o aeroporto mais movimentado da região Norte em passageiros transportados, ocupando a 14º colocação no ranking dos maiores aeroportos do Brasil, sendo a principal porta de entrada da Amazônia brasileira. Mais informações no  <a href="http://www.infraero.gov.br/index.php/br/aeroportos/para/aeroporto-internacional-de-belem/companhias-aereas.html">website</a>.'}
 - {title: "Transporte público", information: 'Belém conta com uma repleta frota de ônibus em que você poderá utilizar no valor (Inteira R$ 2,70) e (Meia R$ 1,35). Indicamos utilizar o aplicativo (Rota Urbana) desenvolvido por paraenses para encontra as linhas de ônibus. Cooperativas de Táxi http://www.cooperdoca.com.br/ BASÍLICA NAZARÉ: 3224-2106 Indicamos utilizar os aplicativos Easy Taxi ou 99Taxis que funcionam muito bem na região metropolitana de Belém.'}
 - {title: "Hotéis", information: 'Próximos do local do evento: <a href="http://www.hotelhangar.com.br">www.hotelhangar.com.br</a> <a href="http://www.tulipinnhangar.com/pt-pt">www.tulipinnhangar.com/pt-pt</a> <a href="http://www.hotelvaldecans.com.br/">www.hotelvaldecans.com.br</a> <a href="http://www.ibis.com/pt-br/hotel-5631-ibis-belem-aeroporto/index.shtml">www.ibis.com/pt-br/hotel-5631-ibis-belem-aeroporto/index.shtml</a>'}
directionDetailsWideCards:
 -
  title: "Dúvidas?"
  subCards:
   -
    title: "Hotéis"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Conheça nossos temas"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
